### ISSUE TITLE
遇到的一些问题和建议

### ISSUE THREAD

**Issue by yj94** [HackerCalico/Magic_C2#2]
这个项目真的很不错，亲切的.net，但我现在发现一些问题和建议：
本人存在的问题：
1.客户端 文件管理会导致未知原因导致崩溃
2.客户端 监听端口会重复
3.服务端 using (SQLiteConnection conn = new SQLiteConnection(@"Data Source = config\client.db")) 返回为空
	我个人在此前面加了个try catch捕获异常 程序就可以跑了
4.客户端 脚本的调用有问题 python已添加到环境变量 且使用的是默认的脚本 调用时c2进程会崩溃

建议可以改进优化的功能：
1.沙箱判断数据功能 可自定义
2.当有提醒信息 例如：未授权访问的c2 的时候托盘尽量不显示，导致太多图标了 若心跳很小的话
3.profile文件定义更直观点就好了

自己使用了一会得到的一些结论，希望大佬加油，非常看好这个项目！

**Comment by HackerCalico** [comment]
有点晚了，你的问题我感觉有一种可能，就是你直接编译运行了客户端的 Release。
你可以看一下 Debug 中有 config、tools、tmp 三个文件夹，需要自己复制到 Release 中。数据库和插件都在 config 中。
端口重复和弹未授权我感觉可能是一个问题，就是你的服务端端口与监听器端口重复了，导致数据也无法正确解析产生未授权。

**Comment by yj94** [comment]
嗯，我全程用的都是debug版本。总体来说问题都是不影响整体的，只有部分功能可能我个人测会崩溃。这个监听端口重复，我的意思是添加监听器的时候不会判断端口是否重复导致有端口重复监听的意思。其他没啥了，知道此项目开放时间短，但做的已经非常不错了。感谢回复！
